<a href="https://colab.research.google.com/github/DeepandraSingh1225/Machine-lerning/blob/main/Magic_gamma_telescope.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [79]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import RandomOverSampler

#Dataset
- https://archive.ics.uci.edu/dataset/159/magic+gamma+telescope

Additional Variable Information

    - 1.  fLength:  continuous  # major axis of ellipse [mm]
    - 2.  fWidth:   continuous  # minor axis of ellipse [mm]
    - 3.  fSize:    continuous  # 10-log of sum of content of all pixels [in #phot]
    - 4.  fConc:    continuous  # ratio of sum of two highest pixels over fSize  [ratio]
    - 5.  fConc1:   continuous  # ratio of highest pixel over fSize  [ratio]
    - 6.  fAsym:    continuous  # distance from highest pixel to center, projected onto major axis [mm]
    - 7.  fM3Long:  continuous  # 3rd root of third moment along major axis  [mm]
    - 8.  fM3Trans: continuous  # 3rd root of third moment along minor axis  [mm]
    - 9.  fAlpha:   continuous  # angle of major axis with vector to origin [deg]
    - 10.  fDist:    continuous  # distance from origin to center of ellipse [mm]
    - 11.  class:    g,h         # gamma (signal), hadron (background)

   - g = gamma (signal):     12332
   - h = hadron (background): 6688

   - For technical reasons, the number of h events is underestimated. In the real data, the h class represents the majority of the events.

In [80]:
df = pd.read_csv('magic04.data')
df

,28.7967,16.0021,2.6449,0.3918,0.1982,27.7004,22.011,-8.2027,40.092,81.8828,g
0,31.6036,11.7235,2.5185,0.5303,0.3773,26.2722,23.8238,-9.9574,6.3609,205.2610,g
1,162.0520,136.0310,4.0612,0.0374,0.0187,116.7410,-64.8580,-45.2160,76.9600,256.7880,g
2,23.8172,9.5728,2.3385,0.6147,0.3922,27.2107,-6.4633,-7.1513,10.4490,116.7370,g
3,75.1362,30.9205,3.1611,0.3168,0.1832,-5.5277,28.5525,21.8393,4.6480,356.4620,g
4,51.6240,21.1502,2.9085,0.2420,0.1340,50.8761,43.1887,9.8145,3.6130,238.0980,g
...,...,...,...,...,...,...,...,...,...,...,...
19014,21.3846,10.9170,2.6161,0.5857,0.3934,15.2618,11.5245,2.8766,2.4229,106.8258,h
19015,28.9452,6.7020,2.2672,0.5351,0.2784,37.0816,13.1853,-2.9632,86.7975,247.4560,h
19016,75.4455,47.5305,3.4483,0.1417,0.0549,-9.3561,41.0562,-9.4662,30.2987,256.5166,h
19017,120.5135,76.9018,3.9939,0.0944,0.0683,5.8043,-93.5224,-63.8389,84.6874,408.3166,h
19018,187.1814,53.0014,3.2093,0.2876,0.1539,-167.3125,-168.4558,31.4755,52.7310,272.3174,h

- we don't have Attributes name or column name in this data set so we add this in our df

In [81]:
cols = ["fLength", "fWidth", "fSize", "fConc", "fConc1", "fAsym", "fM3Long", "fM3Trans", "fAlpha", "fDist", "class"]

# df = pd.read_csv('magic04.data' , names=labels)
# df.head()

# OR


df.columns = cols
df.head()

,fLength,fWidth,fSize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist,class
0,31.6036,11.7235,2.5185,0.5303,0.3773,26.2722,23.8238,-9.9574,6.3609,205.261,g
1,162.0520,136.0310,4.0612,0.0374,0.0187,116.7410,-64.8580,-45.2160,76.9600,256.788,g
2,23.8172,9.5728,2.3385,0.6147,0.3922,27.2107,-6.4633,-7.1513,10.4490,116.737,g
3,75.1362,30.9205,3.1611,0.3168,0.1832,-5.5277,28.5525,21.8393,4.6480,356.462,g
4,51.6240,21.1502,2.9085,0.2420,0.1340,50.8761,43.1887,9.8145,3.6130,238.098,g

- we can clearly see that we have class 'g' and 'h'

In [82]:
df['class'].unique()

array(['g', 'h'], dtype=object)

- our computer don't understand calegorical data so we have to conver this g and h into numbers or numerical data

In [83]:
df['class'] = (df['class'] == 'g').astype(int)      # g = 1 and h = 0

In [84]:
df.head()

,fLength,fWidth,fSize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist,class
0,31.6036,11.7235,2.5185,0.5303,0.3773,26.2722,23.8238,-9.9574,6.3609,205.261,1
1,162.0520,136.0310,4.0612,0.0374,0.0187,116.7410,-64.8580,-45.2160,76.9600,256.788,1
2,23.8172,9.5728,2.3385,0.6147,0.3922,27.2107,-6.4633,-7.1513,10.4490,116.737,1
3,75.1362,30.9205,3.1611,0.3168,0.1832,-5.5277,28.5525,21.8393,4.6480,356.462,1
4,51.6240,21.1502,2.9085,0.2420,0.1340,50.8761,43.1887,9.8145,3.6130,238.098,1

In [ ]:
for label in cols[:-1]:  # run on each feature except class

  plt.hist(df[df['class'] == 1][label] , label='gamma' , alpha = 0.7 , density=True)
  plt.hist(df[df['class'] == 0][label] ,  label='hadron' , alpha = 0.7 , density=True)
  # this line f[df['class'] == 1][label]  all the features or label where class is 1

  plt.title(label)
  plt.ylabel('probability')
  plt.xlabel(label)
  plt.legend()
  plt.show()

  # density=True -> normalizes the histogram so that the area under its bars sums to 1. This is useful for comparing distributions regardless of the number of samples in each class.

## Train , Validation and Test Dataset

In [86]:
train , valid , test = np.split(df.sample(frac=1) , [int(0.6*len(df)) , int(0.8*len(df))])
# 0 to 60% train , 60 to 80 valid , 80 to 100 test
# frac = 1 arrange data randomly

/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:57: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

In [87]:
# so now we can see that the value scale are too much in dataset

def scale_dataset(dataframe , oversample = False):

  x = dataframe[dataframe.columns[:-1]].values
  y = dataframe[dataframe.columns[-1]].values

  scaler = StandardScaler()
  x = scaler.fit_transform(x)            # it scale the values

  if oversample :
    ros = RandomOverSampler()
    x , y = ros.fit_resample(x , y)   # below we can see the diff bw x and y values so sample help to manage it


  data = np.hstack((x, np.reshape(y, (-1, 1))))     # we know that y is in vector whare as x is in matrix form so we have to reshape it
  # here (-1,1) is like (len(y) , 1)
  return data , x, y

In [88]:
# print(len(train[train['class'] == 1])) # gamma
# print(len(train[train['class'] == 0])) # hadron

7441
3970

In [92]:
# as the diff bw len of gamma and hadron values we can potentially get error so we scale it
#now after oversample

train , x_train , y_train = scale_dataset(train , oversample = True)
valid , x_valid , y_valid = scale_dataset(valid , oversample = False)      # we dont oversample the valid and test data because we have to see if the model can work on random
test , x_test , y_test = scale_dataset(test , oversample = False)

In [93]:
len(y_train[y_train == 1])

7441

In [94]:
len(y_train[y_train == 0])

7441

# kNN (k nearest neighbour)

In [103]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

In [111]:
knn_model = KNeighborsClassifier(n_neighbors=3)
knn_model.fit(x_train , y_train)

KNeighborsClassifier(n_neighbors=3)

In [105]:
y_pred = knn_model.predict(x_test)
y_pred

array([1, 0, 1, ..., 1, 0, 1])

In [106]:
y_test

array([1, 0, 1, ..., 1, 0, 1])

- we can clearly see that the values that we predic and actual value are very much close

In [109]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.79      0.68      0.73      1364
           1       0.84      0.90      0.87      2440

    accuracy                           0.82      3804
   macro avg       0.81      0.79      0.80      3804
weighted avg       0.82      0.82      0.82      3804